#!/usr/bin/env bash
cd ~/workspace/master-risc-v/ibex-demo-system/
source .venv/bin/activate

# export RISCV=~/tools/lowrisc/lowrisc-toolchain-rv32imcb-20220524-1
export RISCV=~/tools/riscv-embecosm/riscv-embecosm-embedded-ubuntu2204-20240407
export PATH=$RISCV/bin:$PATH
