sub-visibility=yes
sub-auto=fuzzy
alang=en,es
slang=en,es
audio-file-auto=fuzzy
save-position-on-quit=yes
autofit-larger=100%x100%
geometry=50%:50%
stop-screensaver = "yes"
sub-font="Dejavu Sans"
sub-font-size=36
sub-color="#ffffff00"
sub-border-color="#FF262626"
sub-border-size=3.2
sub-shadow-offset=1
sub-shadow-color="#33000000"
sub-spacing=0.5